import keyMirror from 'keymirror';

const action = keyMirror({
  // ajax calls
  BEGIN_AJAX_CALL: null,
  AJAX_CALL_ERROR: null,

  // rank actions
  LOAD_RANKS_SUCCESS: null,
  LOAD_RANKS_FAILED: null,
  LOAD_RANK_SUCCESS: null,
  LOAD_RANK_FAILED: null,
  CREATE_RANK_SUCCESS: null,
  CREATE_RANK_FAILED: null,
  UPDATE_RANK_SUCCESS: null,
  UPDATE_RANK_FAILED: null,
  DELETE_RANK_SUCCESS: null,
  DELETE_RANK_FAILED: null,

  // phone actions
  LOAD_PHONES_SUCCESS: null,
  LOAD_PHONES_FAILED: null,
  LOAD_PHONE_SUCCESS: null,
  LOAD_PHONE_FAILED: null,
  CREATE_PHONE_SUCCESS: null,
  CREATE_PHONE_FAILED: null,
  UPDATE_PHONE_SUCCESS: null,
  UPDATE_PHONE_FAILED: null,
  DELETE_PHONE_SUCCESS: null,
  DELETE_PHONE_FAILED: null,

  // email actions
  LOAD_EMAILS_SUCCESS: null,
  LOAD_EMAILS_FAILED: null,
  LOAD_EMAIL_SUCCESS: null,
  LOAD_EMAIL_FAILED: null,
  CREATE_EMAIL_SUCCESS: null,
  CREATE_EMAIL_FAILED: null,
  UPDATE_EMAIL_SUCCESS: null,
  UPDATE_EMAIL_FAILED: null,
  DELETE_EMAIL_SUCCESS: null,
  DELETE_EMAIL_FAILED: null,

  // student actions
  LOAD_STUDENTS_SUCCESS: null,
  LOAD_STUDENTS_FAILED: null,
  LOAD_STUDENT_SUCCESS: null,
  LOAD_STUDENT_FAILED: null,
  CREATE_STUDENT_SUCCESS: null,
  CREATE_STUDENT_FAILED: null,
  UPDATE_STUDENT_SUCCESS: null,
  UPDATE_STUDENT_FAILED: null,
  DELETE_STUDENT_SUCCESS: null,
  DELETE_STUDENT_FAILED: null,

// student address actions
 LOAD_STUDENT_ADDRESSES_SUCCESS: null,
 LOAD_STUDENT_ADDRESSES_FAILED: null,
 LOAD_STUDENT_ALL_ADDRESSES_SUCCESS: null,
 LOAD_STUDENT_ALL_ADDRESSES_FAILED: null,
 CREATE_STUDENT_ADDRESS_SUCCESS: null,
 UPDATE_STUDENT_ADDRESS_SUCCESS: null,
 CREATE_STUDENT_ADDRESS_FAILED: null,
 UPDATE_STUDENT_ADDRESS_FAILED: null,
 DELETE_STUDENT_ADDRESS_SUCCESS: null,
 DELETE_STUDENT_ADDRESS_FAILED: null,

  // academy actions
  LOAD_ACADEMIES_SUCCESS: null,
  LOAD_ACADEMIES_FAILED: null,
  LOAD_ACADEMY_SUCCESS: null,
  LOAD_ACADEMY_FAILED: null,
  CREATE_ACADEMY_SUCCESS: null,
  UPDATE_ACADEMY_SUCCESS: null,
  CREATE_ACADEMY_FAILED: null,
  UPDATE_ACADEMY_FAILED: null,
  DELETE_ACADEMY_SUCCESS: null,
  DELETE_ACADEMY_FAILED: null,

  // state actions
  LOAD_ACADEMYADDRESSES_SUCCESS: null,
  LOAD_ACADEMYADDRESSES_FAILED: null,

  // state actions
  LOAD_STATES_SUCCESS: null,
  LOAD_STATES_FAILED: null,

  // address actions
  LOAD_ADDRESSES_SUCCESS: null,
  LOAD_ADDRESSES_FAILED: null,
  LOAD_ADDRESS_SUCCESS: null,
  LOAD_ADDRESS_FAILED: null,
  CREATE_ADDRESS_SUCCESS: null,
  UPDATE_ADDRESS_SUCCESS: null,
  CREATE_ADDRESS_FAILED: null,
  UPDATE_ADDRESS_FAILED: null,
  DELETE_ADDRESS_SUCCESS: null,
  DELETE_ADDRESS_FAILED: null,

  // address type actions
  LOAD_ADDRESES_TYPES_SUCCESS: null,
  LOAD_ADDRESES_TYPES_FAILED: null,
  LOAD_ADDRESS_TYPES_SUCCESS: null,
  LOAD_ADDRESS_TYPES_FAILED: null,
  CREATE_ADDRESS_TYPE_SUCCESS: null,
  UPDATE_ADDRESS_TYPE_SUCCESS: null,
  CREATE_ADDRESS_TYPE_FAILED: null,
  UPDATE_ADDRESS_TYPE_FAILED: null,
  DELETE_ADDRESS_TYPE_SUCCESS: null,
  DELETE_ADDRESS_TYPE_FAILED: null,

  // student status actions
  LOAD_STATUSES_SUCCESS: null,
  LOAD_STATUSES_FAILED: null,
  LOAD_STATUS_SUCCESS: null,
  LOAD_STATUS_FAILED: null,
  CREATE_STATUS_SUCCESS: null,
  UPDATE_STATUS_SUCCESS: null,
  CREATE_STATUS_FAILED: null,
  UPDATE_STATUS_FAILED: null,
  DELETE_STATUS_SUCCESS: null,
  DELETE_STATUS_FAILED: null,

  // state actions
  LOAD_ACADEMY_ADDRESSES_SUCCESS: null,
  LOAD_ACADEMY_ADDRESSES_FAILED: null
});

export default action;
